# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 01:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
            ],
        ),
    ]
