# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 02:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineEditorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
